### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by coelho5br** [yokawasa/azure-webapps-logging-original-clientip#1]
The F5 Link is broken
http://devcentral.f5.com/downloads/codeshare/F5XForwardedFor.zip

**Comment by yokawasa** [comment]
Thanks for your posing this.
I fixed:
- https://github.com/yokawasa/azure-webapps-logging-original-clientip/commit/bd7011dbfb6f5d0fd70c759491e4d90c928b4608
